// Định nghĩa tên biến
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const DEVIDE = 'DEVIDE';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const REGIS_USER_REQUEST = 'REGIS_USER_REQUEST';
export const REGIS_USER_SUCCESS = 'REGIS_USER_SUCCESS';
export const REGIS_USER_FAILURE = 'REGIS_USER_FAILURE';

export const ACNE_DETECTION_DAILY_REQUEST = 'ACNE_DETECTION_DAILY_REQUEST';
export const ACNE_DETECTION_DAILY_SUCCESS = 'ACNE_DETECTION_DAILY_SUCCESS';
export const ACNE_DETECTION_DAILY_FAILURE = 'ACNE_DETECTION_DAILY_FAILURE';
export const ACNE_DETECTION_DAILY_CROP_EDIT = 'ACNE_DETECTION_DAILY_CROP_EDIT'